apiVersion: keda.sh/v1alpha2
kind: ScaledObject
metadata:
  name: orderservice-scaler
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: orderservice
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      queueName: pedidos
      mode: QueueLength
      value: "2000"
      host: "amqp://admin:admin@rabbitmq:5672/"